feat: add gov v3 helpers
aave-dao/aave-helpers pull request #139
Opened 2023-08-18 11:18 UTC by sendra

2023-08-22 11:58 UTC, sakulstra commented on src/GovV3Helpers.sol
> +  function executePayload(Vm vm, uint40 payloadId) internal {
Should probably have an overload like:
`  function executePayload(Vm vm, address payloadAddress) internal {`
creating the payload first

2023-09-20 10:02 UTC, sendra commented on src/GovV3Helpers.sol
> +    for (uint40 payloadId = count - 1; payloadId >= 0; payloadId++) {
should be payloadId--

2023-09-20 10:03 UTC, sakulstra commented on src/GovV3Helpers.sol
> +    for (uint40 payloadId = count - 1; payloadId >= 0; payloadId++) {
```suggestion
    for (uint40 payloadId = count - 1; payloadId >= 0; payloadId--) {
```

2023-10-09 11:18 UTC, sendra commented on src/ChainIds.sol
> +      newFork = vm.createFork(vm.rpcUrl('tkSync'));
```suggestion
      newFork = vm.createFork(vm.rpcUrl('zkSync'));
```

2023-10-09 11:55 UTC, rustboyar commented on src/GovV3Helpers.sol
> +   * Registers a payload with the provided actions on the networjḱ PayloadsController
networjk -> network

2023-10-09 12:23 UTC, rustboyar approved these changes

2023-10-09 12:37 UTC, kyzia551 requested changes

2023-10-09 12:37 UTC, kyzia551 commented on .env.example
Should it also include `Sepolia`?
I see it exists in `foundry.toml`

2023-10-09 12:37 UTC, kyzia551 commented on src/GovV3Helpers.sol
> +  }
```suggestion
  function createPayload(
    IPayloadsControllerCore.ExecutionAction memory action
  ) internal returns (uint40) {
    IPayloadsControllerCore.ExecutionAction[]
      memory actions = new IPayloadsControllerCore.ExecutionAction[](1);
    actions[0] = action;
    return createPayload(actions);
  }
```

2023-10-09 12:37 UTC, kyzia551 commented on src/GovV3Helpers.sol
> +  }
```suggestion
  function _buildPayload(
    Vm vm,
    uint256 chainId,
    IPayloadsControllerCore.ExecutionAction memory action
  ) internal returns (PayloadsControllerUtils.Payload memory) {
    IPayloadsControllerCore.ExecutionAction[]
      memory actions = new IPayloadsControllerCore.ExecutionAction[](1);
    actions[0] = action;
    return _buildPayload(vm, chainId, actions);
  }
```

2023-10-12 13:19 UTC, kyzia551 approved these changes

2023-10-12 16:29 UTC, merged