Aave Swapper - TWAP Orders
aave-dao/aave-helpers pull request #225
Opened 2024-01-20 13:04 UTC by efecarranza

# Changelog

Add TWAP orders to the Aave Swapper contract.
Add tests for TWAP orders.
Add documentation to README.

Builds on top of: https://github.com/bgd-labs/aave-helpers/pull/201

2024-01-25 12:19 UTC, brotherlymite commented on src/swaps/AaveSwapper.sol
> +    address relayer,
@efecarranza does it make sense to make these params as immutable?

2024-01-26 13:24 UTC, efecarranza commented on src/swaps/AaveSwapper.sol
> +    address relayer,
hey @brotherlymite when building the original AaveSwapper, feedback was provided that we should be allowed to pass the specific price checker, so that's why I went with that route for this even though they are not a price checker, but kind of the same concept. We could have it as a contract variable that can be updated as well in case of changes to the cow swap relayer or handler, though I doubt those values are likely to change.

@eboado If my memory serves me well, I think you and I had discussed this approach. Wanted to see if you had any thoughts around it. Thank you

2025-04-14 13:09 UTC, pavelvm5 requested changes

2025-04-14 13:09 UTC, pavelvm5 commented on .gitmodules
Could you update `composable-cow` lib? Cause it has `balancer` lib inside, which can't be installed right now.

At least I don't have access to it. But the more fresh commit doesn't have such lib in it.

2025-04-14 13:09 UTC, pavelvm5 commented on scripts/AaveSwapperDeployment.s.sol
> +    TransparentProxyFactory(MiscEthereum.TRANSPARENT_PROXY_FACTORY).create(
```suggestion
    ITransparentProxyFactory(MiscEthereum.TRANSPARENT_PROXY_FACTORY).create(
```

2025-04-14 13:09 UTC, pavelvm5 commented on src/swaps/AaveSwapper.sol
> +    );
Function in interface has 7 arguments, not 6. `appData` was skipped.

2025-04-14 15:37 UTC, closed without merging