WIP: Aave stETH native withdrawer
aave-dao/aave-helpers pull request #307
Opened 2024-07-01 17:13 UTC by defijesus

2024-07-01 23:11 UTC, efecarranza commented on src/asset-manager/AaveStethWithdrawer.sol
> +    IERC20(AaveV3EthereumAssets.wstETH_UNDERLYING).approve(
I would do the approvals on startWithdraw

2024-07-01 23:11 UTC, efecarranza commented on src/asset-manager/AaveStethWithdrawer.sol
> +    reqIds = requestIds[index];
I think `return requestIds[index]` is a bit more readable for such a small function

2024-07-01 23:11 UTC, efecarranza commented on src/asset-manager/interfaces/IAaveStethWithdrawer.sol
> +  /// @notice emited when a new Withdrawal is requested
emitted, typo

2024-07-01 23:11 UTC, efecarranza commented on src/asset-manager/interfaces/IAaveStethWithdrawer.sol
> +  /// @param amounts a list of amounts to be withdrawn. each amount must be > 100 wei and < 1000 ETH
If these are the min/max, I'd add these checks and revert.

2024-07-01 23:11 UTC, efecarranza commented on tests/asset-manager/AaveStethWithdrawerTest.t.sol
> +    emit StartedWithdrawal(amounts, 0);
Shouldn't this be index 1? You're doing nextId++ before assigning

2024-07-04 23:15 UTC, defijesus commented on src/asset-manager/interfaces/IAaveStethWithdrawer.sol
> +  /// @param amounts a list of amounts to be withdrawn. each amount must be > 100 wei and < 1000 ETH
the requestWithdrawalsWstETH() call to the WSETH_WITHDRAWAL_QUEUE already reverts if amounts are outside bounds

2024-07-04 23:17 UTC, defijesus commented on src/asset-manager/AaveStethWithdrawer.sol
> +    IERC20(AaveV3EthereumAssets.wstETH_UNDERLYING).approve(
Doing a single approval for max, greatly cleans up the code of startWithdraw. To do approvals only for the amounts needed we would need to go over the amounts array and sum it. Considering this I still think this design is simpler.

2024-07-07 10:34 UTC, kyzia551 requested changes

2024-07-07 10:34 UTC, kyzia551 commented on src/asset-manager/AaveStethWithdrawer.sol
> +  uint256 public nextIndex;
I think that`nextRequestIndex` will be a better name, or something about withdraw

But actually it's not next, but current, because you do ++ straight away in the `startWithdraw` func

2024-07-07 10:34 UTC, kyzia551 commented on src/asset-manager/AaveStethWithdrawer.sol
> +// import {Rescuable721} from 'solidity-utils/contracts/utils/Rescuable721.sol';
please update

2024-07-07 10:34 UTC, kyzia551 commented on src/asset-manager/AaveStethWithdrawer.sol
> +
Please add credits about author, etc

2024-07-07 10:34 UTC, kyzia551 commented on src/asset-manager/AaveStethWithdrawer.sol
> +    uint256 index = nextIndex++;
why don't you start from 0?

2024-07-07 10:34 UTC, kyzia551 commented on src/asset-manager/interfaces/IAaveStethWithdrawer.sol
> +  event StartedWithdrawal(uint256[] amounts, uint256 index);
make `index` indexed

2024-07-07 10:34 UTC, kyzia551 commented on src/asset-manager/interfaces/IAaveStethWithdrawer.sol
> +  event FinalizedWithdrawal(uint256 amount, uint256 index);
make `index` indexed

2024-07-07 10:34 UTC, kyzia551 commented on tests/asset-manager/AaveStethWithdrawerTest.t.sol
> +// }
update

2024-07-11 09:34 UTC, eboadom commented on src/asset-manager/AaveStethWithdrawer.sol
> +  constructor(address owner) {
Any rationale to pass here the executor as parameter, instead of using directly from address book? Considering that this contract is already very coupled to Ethereum with the usage of `AaveV3Ethereum.COLLECTOR` later on

2024-07-11 09:38 UTC, eboadom commented on src/asset-manager/AaveStethWithdrawer.sol
> +  mapping(uint256 => uint256[]) public requestIds;
Given that this is `public` already, probably doesn't make sense to expose the other `getRequestIds()`

2024-07-11 09:38 UTC, eboadom commented on src/asset-manager/AaveStethWithdrawer.sol
> +    uint256[] memory reqIds = getRequestIds(index);
Minor, but why using the getter instead of the `requestIds` var?

2024-07-11 09:54 UTC, eboadom commented on src/asset-manager/AaveStethWithdrawer.sol
> +      1,
My understanding is that `getLastRequestId()` is always incremental, so even if this is only used to limit the binary search, wouldn't make more sense to instead of `1` initialize in a constant/immutable on this contract the value of `getLastRequestId()`?

Because if not it would be the same as using `function claimWithdrawal(uint256 _requestId) external {` later on instead of `claimWithdrawalsTo()`

2024-07-12 09:08 UTC, eboadom commented
Some interesting "vector" (don't see any danger, but better to think about it): somebody could donate ETH to the contract while having an active (not withdrawn) stETH order, and `finalizeWithdraw()` would add the amount to withdraw from stETH + the balance of the contract from the donation.

2024-07-12 09:23 UTC, eboadom commented
Something that I don't fully understand high-level. Wouldn't be reasonable to make use of `onERC721Received()` on `AaveStethWithdrawer`?

2024-07-12 09:35 UTC, eboadom commented on tests/asset-manager/AaveStethWithdrawerTest.t.sol
> +    /// At current block 0x3169db has an Lido withdrawal NFT
Is it really needed this complexity instead of reproducing an account withdrawal? This way you are coupling the tests completely to the fork block

2024-07-12 14:21 UTC, defijesus commented on src/asset-manager/AaveStethWithdrawer.sol
> +  constructor(address owner) {
main rational was to not need to update this code when updating the governance contracts to the next version.

from v2 to v3 we saw some changes on the executor side of things, I assume with v4 we'll see some changes too

2024-07-12 14:27 UTC, defijesus commented on src/asset-manager/AaveStethWithdrawer.sol
> +      1,
I followed the usage recommendation @ the source code of findCheckpointHints here:

https://etherscan.io/address/0xe42c659dc09109566720ea8b2de186c2be7d94d9#code#F22#L293

Will update contract to store an immutable checkpoint on contract creation to prune all older request ids from the binary search

2024-07-12 14:30 UTC, defijesus commented
> Something that I don't fully understand high-level. Wouldn't be reasonable to make use of `onERC721Received()` on `AaveStethWithdrawer`?

would be needed if stETH system would call such callback. from my understanding onERC721Received() only triggers if safeTransferFrom is used (which is not the case here)

2024-07-12 14:33 UTC, defijesus commented on tests/asset-manager/AaveStethWithdrawerTest.t.sol
> +    /// At current block 0x3169db has an Lido withdrawal NFT
from my cursory understanding of Lido systems, we would need to mock a lot more calls, and a lot more of Lidos internal systems, to make our test withdrawal available to be finalized.

imo, using the current solution leads to a cleaner tests that focus on testing the actual Withdrawer functionality vs Lido internal workings.

2024-07-13 06:43 UTC, eboadom commented on src/asset-manager/AaveStethWithdrawer.sol
> +  constructor(address owner) {
My point is that even if you want to use a variable owner (to transfer ownership later), I don't see much reason to pass it from outside, because this contract is designed to be one per network, same as Collector

2024-07-13 06:48 UTC, eboadom commented on tests/asset-manager/AaveStethWithdrawerTest.t.sol
> +    /// At current block 0x3169db has an Lido withdrawal NFT
By being invasive (etching, swapping storage) on external systems, it is even difficult to evaluate how close is the test to production. Meaning that maybe will work here and not in production

Take into account that the reviewer (us) don't know in depth that component in Lido, so we simply can't say if this test is legit or not when using cheatcodes. Looks so, but still

2024-07-22 18:28 UTC, eboadom approved these changes

2024-07-23 09:27 UTC, merged